name: test-runner
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Say hello
        run: |
          echo "Runner: $RUNNER_NAME"
          uname -a
